### ISSUE TITLE
Create a very simple end-to-end example to run a QA workflow

### ISSUE THREAD

**Issue by agstephens** [EO-DataHub/eodh-qa-prototype#3]
### Proposed plan...

**Input data:**
- **Collection**: https://api.stac.ceda.ac.uk/eo/collections/Sentinel-2A
- **Item**: https://api.stac.ceda.ac.uk/eo/collections/Sentinel-2A/items/6d010854a589dd5980442d7947be6233574ab442

**Simple python code as the QA checker:**
- N functions that check the STAC content
- function names should indicate what the check does

**Output:**
- 1 JSON file containing anything relevant:
  - per-metric results (including details, links etc)
  - general metadata about the specification, etc.:
    - probably with _dead_ links to *future* documents/sites
    - author, date created, version and description of software environment

**Comment by shunt16** [comment]
Minimal QA check prototype now in 3-example_workflow branch

**Comment by shunt16** [comment]
Extend to include:

* Run multiple tests in single process?
* Handling of logging
* Interaction with event and notification service
* Control vocabulary?
* unittest
* yaml for tests per collection
* some kind of container of checks
